## Hacker earth exam problems

- 1. Avg of the length 3 numbered elements

- 2. Finding the minimum distance between the elements in a test case line

- 3. Extact the urls with non uniques

In [13]:
def avg(li):
    u=[]
    sum=0
    c=0
    for i in li:
        if i not in u:
            u.append(i) 
    #rint(u)
    #=list(filter(lambda i: len(str(i))==3,u))
    #rint(l)
    for i in u:
        if len(str(i))==3:
            sum=sum+int(i)
            c=c+1
    return sum//c    
li=input().split()
avg(li)
    
        

1 100 200 100 2 3 4


150

In [134]:
def minimumdif(li):
    u=[]
    for i in range(len(li)-1):
        for j in range(i+1,len(li)):
            d=abs(int(li[i])-int(li[j]))
            if d not in u:
                u.append(d)
    print(min(u))
t=int(input())
for i in range(t):
    li=input().split()
    minimumdif(li)

3
6 3 9 15
3
1 2 3 4 5
1
100 20 50 108
8


In [16]:
def urls(li):
    t=int(input())
    u=[]
    u1={}
    for i in range(t):
        li=input() 
        u.append(li) 
        for i in u:
            if i not in u1:
                u1[i]=1
            else:
                u1[i]+=1
    print(u1)    
urls(li)

5
fvkdf
fkdf
dkfjkds
dkf
dfk
{'fvkdf': 5, 'fkdf': 4, 'dkfjkds': 3, 'dkf': 2, 'dfk': 1}


In [103]:
# Function to generate the key for encription

keypath='DataFiles\key.txt'
def generatekey():
    with open(keypath,'w') as f:
        for i in range(10):
            if i <6:
                f.write(str(i)+' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
generatekey()
        
        

In [102]:
# Function to encrypt a data file 
keyfile='DataFiles\key.txt'
def dictionarykeyFile(keyfile):
    key={}
    with open (keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
dictionarykeyFile(keyfile)

#def encryptMarksData(datafile,keyfile):
    # construct a dictionary   for key data 

{'0': '4',
 '1': '5',
 '2': '6',
 '3': '7',
 '4': '8',
 '5': '9',
 '6': '0',
 '7': '1',
 '8': '2',
 '9': '3'}

In [104]:
# dictionaryKey File encryption of marks

def encryptMarksData(datafile,keyfile):
    # Construct a dictionary for key data
    key=dictionarykeyFile(keyfile)
    with open (datafile,'r') as f:
        filedata=f.read().split('\n')
    with open ('DataFiles\encryptedMarks.txt','w') as f:
        for mark in filedata:
            line= ''
            for  n in mark:
                line+=key[n]
            f.write(line+'\n')
    return
datafile='D\marks.txt'
keyfile='DataFiles\key.txt'

encryptMarksData(datafile,keyfile)
            
    
                
        

In [105]:
def decryptMarksData(encryptfile,keyfile):
    key=dictionarykeyFile(keyfile)
    newkey={}
    for key ,value in key.items():
        newkey[value]=key
        
    with open (encryptfile,'r') as f:
        encrypteddata=f.read().split('\n')
    with open ('DataFiles\decryptMarksData','w') as f:        
        for encryptedmark in encrypteddata:
            line=''
            for n in encryptedmark:
                line+=newkey[n]
            f.write(line+'\n')
    return
encryptfile='DataFiles\encryptedMarks.txt'
keyfile='DataFiles\key.txt'
import timeit
st=timeit.default_timer()
decryptMarksData(encryptfile,keyfile)
print(timeit.default_timer()-st)
        

0.018870143999720312


In [106]:
key=dictionarykeyFile(keyfile)
key

{'0': '4',
 '1': '5',
 '2': '6',
 '3': '7',
 '4': '8',
 '5': '9',
 '6': '0',
 '7': '1',
 '8': '2',
 '9': '3'}

In [26]:
# Comprehensions
keyfile='DataFiles\key.txt'
key=dictionarykeyFile(keyfile)

evenkeys={item for item in key.items() if int(item[0])%2==0}
evenkeys

{('0', '4'), ('2', '6'), ('4', '8'), ('6', '0'), ('8', '2')}

### Numpy Library

- Processing the N-Dimensional Arrays

In [10]:
import numpy as np

li=[1,2,3,'z']
a=np.array(li)
a


#type(a)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
b=np.arange(15)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
x=np.random.randint(0,100,size=10)
x

array([82, 70, 73, 16, 30, 46, 96, 23,  7, 31])

In [43]:
m2=np.random.randint(0,2,size=(3,3))
m2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [71]:
m2[:2,:3] # First two rows and first two columns

array([[1, 0, 0],
       [1, 0, 0]])

In [72]:
m2[:3,::2] # first and third columns


array([[1, 0],
       [1, 0],
       [1, 1]])

In [73]:
m2[::-1,::-1] # Transposing (rows -columns and columns rows)

array([[1, 1, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [77]:
print(m2[:,1])

[0 0 1]


In [78]:
# copy..... Copy function u have to add syamu see in sirs github
m2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [96]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
#

In [44]:
m2[1][0]

1

In [49]:
m2.ndim

2

In [50]:
m2.size

9

In [51]:
m2.shape

(3, 3)

In [60]:
m2.dtype

dtype('int32')

In [63]:
m2.itemsize

4

In [65]:
m2.nbytes

36

In [45]:
m3=np.random.randint(0,2,size=(3,3,3,3))
m3

array([[[[0, 0, 1],
         [1, 0, 1],
         [1, 1, 0]],

        [[0, 1, 0],
         [1, 0, 0],
         [1, 1, 1]],

        [[0, 1, 0],
         [0, 0, 0],
         [1, 1, 1]]],


       [[[1, 0, 1],
         [1, 0, 1],
         [0, 0, 1]],

        [[0, 1, 1],
         [0, 1, 0],
         [1, 0, 1]],

        [[1, 1, 0],
         [1, 0, 0],
         [0, 1, 1]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [1, 0, 0]],

        [[1, 0, 0],
         [1, 0, 1],
         [0, 1, 0]],

        [[0, 1, 0],
         [0, 1, 1],
         [0, 0, 0]]]])

In [55]:
m3[0][1][2]

array([1, 1, 1])

In [56]:
m3.ndim

4

In [57]:
m3.size

81

In [58]:
m3.shape

(3, 3, 3, 3)

In [59]:
m3.dtype

dtype('int32')

In [61]:
m3.itemsize

4

In [66]:
m3.nbytes

324

In [67]:
li=[1,2,3,4,5,6,7,8]
li[-5:]

[4, 5, 6, 7, 8]

In [70]:
li[3:len(li)-1]

[4, 5, 6, 7]

### Pandas
***Use cases***
- Data Cleaning
- Data Transformation
- Data Analysis

***Notations***
- Series
- DataFrames


In [7]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':24}
internal1=pd.Series(internal1)
internal1


s1    21
s2    18
s3    24
dtype: int64

In [8]:

internal2={'s1':15,'s2':18,'s3':21}
internal2=pd.Series(internal2)
internal2


s1    15
s2    18
s3    21
dtype: int64

In [15]:
final={' Internal1 ':internal1,' Internal2 ':internal2}

final=pd.DataFrame(final)
final



Internal1    Internal2 
s1           21           15
s2           18           18
s3           24           21

In [17]:

final={' Internal1 ':internal1,' Internal2 ':internal2}

final=pd.DataFrame(final)
final.columns  # List of all columns

Index([' Internal1 ', ' Internal2 '], dtype='object')

In [18]:
final.values # List of all rows

array([[21, 15],
       [18, 18],
       [24, 21]], dtype=int64)

In [19]:
final.values[2]

array([24, 21], dtype=int64)

In [20]:
final.values[2,0] # u can access any table and any value

24

In [32]:
for row in final.values:
   print('Internal1-',row[0],'Internal2-',row[1])
    

Internal1- 21 Internal2- 15
Internal1- 18 Internal2- 18
Internal1- 24 Internal2- 21


In [34]:
final.loc['s4']=[15,18]
final

Internal1    Internal2 
s1           21           15
s2           18           18
s3           24           21
3            15           18
s4           15           18

In [35]:
final.drop(3)

Internal1    Internal2 
s1           21           15
s2           18           18
s3           24           21
s4           15           18

In [38]:
final=final.drop(3)
final

Internal1    Internal2 
s1           21           15
s2           18           18
s3           24           21

In [43]:
final.loc['s4']=[23,12]
final

Internal1    Internal2 
s1           21           15
s2           18           18
s3           24           21
s4           23           12

In [45]:
final.values[2]=[21,24] # Value changed
final

Internal1    Internal2 
s1           21           15
s2           18           18
s3           21           24
s4           23           12

In [47]:
# Reading CSV file data

import pandas as pd

filepath='DataFiles\income.csv'
incomedf = pd.read_csv(filepath)
incomedf


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [48]:
# Extract income of all states in 2013

#California:57528

incomedf.values



array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 47215, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [49]:
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [52]:
# Average income of a particular state (Arizona)

sum=0
for i in range(2,11):
    sum+=incomedf.values[2][i]
avg=sum/len(incomedf.values[2][2:])
print(sum)
print(avg)

424933
47214.77777777778


In [53]:
sum/len(incomedf.values[2][2:])

47214.77777777778

In [55]:
# Average of all states of income 2012

sum=0
for row in incomedf.values:
    sum+=row[-2]
avg=sum/len(incomedf.values)
print(sum)
print(avg)

250194
50038.8
